language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.linuxbrew/
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - glide
    - build-essential
    - jq
    - libprotobuf-c0
    - libprotobuf-c0-dev
    - protobuf-c-compiler
    - libprotobuf-dev
install:
  - cd onnx
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - make install
  - cd $TRAVIS_BUILD_DIR
  - make travis
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
