language: go
matrix:
  include:
    - go: 1.8.x
    - go: 1.9.x
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.linuxbrew/
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - glide
    - build-essential
    - jq
before_install:
  - wget https://github.com/google/protobuf/releases/download/v$PROTOBUF_VER/protoc-$PROTOBUF_VER-linux-x86_64.zip
  - unzip protoc-$PROTOBUF_VER-linux-x86_64.zip -d $HOME/protobuf/
install:
  - cd onnx
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - make install
  - cd $TRAVIS_BUILD_DIR
  - make travis
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)

env:
  global:
  - PROTOBUF_VER="3.5.1"
  - PATH=$HOME/protobuf/bin:$PATH
