language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    - sourceline: ppa:ubuntu-toolchain-r/test
    - sourceline: ppa:maarten-fonville/protobuf
    packages:
    - glide
    - build-essential
    - jq
    - libprotobuf-c0
    - libprotobuf-c0-dev
    - protobuf-c-compiler
    - libprotobuf-dev
    - protobuf-compiler
before_install:
  # setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - cd onnx
  - protoc --cpp_out=. -Iproto -Ionnx onnx.proto onnx-operators.proto
  - mkdir build
  - cd build
  - cmake .. -DONNX_ML=ON -DONNX_NAMESPACE=onnx 
  - make 
  - cd $TRAVIS_BUILD_DIR
  - make travis
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
