language: go
matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip
dist: xenial
sudo: false
addons:
  apt:
    sources:
      - sourceline: ppa:ubuntu-toolchain-r/test
      - sourceline: ppa:maarten-fonville/protobuf
    packages:
      - build-essential
      - protobuf-c-compiler
      - libprotobuf-dev
      - protobuf-compiler
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - cd onnx
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd $TRAVIS_BUILD_DIR
  - make travis
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v
