jobs:
  - job: GPU
    timeoutInMinutes: 0
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_pull_gpu
          make docker_build_gpu
          ./push.sh docker_push_gpu
  - job: Update_Microbadger
    dependsOn:
      - GPU
