//go:generate go get -v github.com/mailru/easyjson/...
//go:generate go get github.com/alvaroloes/enumer
//go:generate go get github.com/jteeuwen/go-bindata/...
//go:generate go get github.com/elazarl/go-bindata-assetfs/...
//go:generate go get github.com/gogo/protobuf/...
//go:generate easyjson -snake_case -disallow_unknown_fields -pkg onnx
//go:generate protoc --gogofaster_out=. -Iproto onnx.proto3

package onnx
