//go:generate go get -v github.com/mailru/easyjson/...
//go:generate go get github.com/alvaroloes/enumer
//go:generate go get github.com/jteeuwen/go-bindata/...
//go:generate go get github.com/elazarl/go-bindata-assetfs/...
//go:generate go get github.com/golang/protobuf/protoc-gen-go
//go:generate go get github.com/gogo/protobuf/...
//go:generate protoc --gogoslick_out=. -Iproto onnx.proto3

package onnx
